    sources:
      - Afacad.glyphs
    axisOrder:
      - slnt
      - wght
    familyName: Afacad
    stat:
      Afacad[slnt,wght].ttf:
      - name: Slant
        tag: slnt
        values:
        - name: Default
          value: 0
          flags: 2
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700