sources:
  - Facade-Stencil.glyphs
familyName: Facade Stencil
# version: 1.000
axisOrder:
  - wght
  - ital
stat:
  Facade-Stencil[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
outputDir: "../../fonts/facade stencil"
buildTTF: true
buildOTF: true
autohintTTF: true
instances:
  Facade-Stencil[wght].ttf:
  - coordinates:
      wght: 400
  - coordinates:
      wght: 500
  - coordinates:
      wght: 600
  - coordinates:
      wght: 700