sources:
  - Afacad.glyphs
familyName: Afacad
# version: 1.000
axisOrder:
  - ital
  - wght
stat:
  Afacad[ital,wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 90
      linkedValue: 1
      flags: 2
    - name: Italic
      value: 104
outputDir: "../../fonts/Afacad"
buildTTF: true
buildOTF: true
autohintTTF: true
